#server:
#  port: 8761
#                  this is for local dev environment
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true

server:
  port: 8761

#eureka:
#  instance:
#    hostname: "${HOSTNAME}.eureka"
#  client:
#    register-with-eureka: false
#    fetch-registry: false
#    serviceUrl:
#      defaultZone: ${EUREKA_SERVER_ADDRESS}