server:
  port: 9191

spring:
  application:
    name: spi-gateway
  cloud:
    gateway:
      routes:
        - id: register-service
          uri: lb://register-service
          predicates:
            - Path=/ecommerce/**
#          filters:
#            - name: CircuitBreaker
#              args:
#                name: register-service
#                fallbackuri: forward:/registerServiceFallBack
        - id: login-service
          uri: lb://login-service
          predicates:
            - Path=/login/**
#          filters:
#            - name: CircuitBreaker
#              args:
#                name: DEPARTMENT-SERVICE
#                fallbackuri: forward:/departmentServiceFallBack

