server:
  port: 9191

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: spi-gateway
  cloud:
    gateway:
      routes:
        - id: register-service
          uri: lb://register-service
          predicates:
            - Path=/ecommerce/**
#          filters:
#            - name: CircuitBreaker
#              args:
#                name: register-service
#                fallbackuri: forward:/registerServiceFallBack
        - id: login-service
          uri: lb://login-service
          predicates:
            - Path=/login/**
#          filters:
#            - name: CircuitBreaker
#              args:
#                name: DEPARTMENT-SERVICE
#                fallbackuri: forward:/departmentServiceFallBack

#eureka:
#  instance:
#    preferIpAddress: true
#    hostname: eureka-0
#  client:
#    registerWithEureka: true
#    fetchRegistry: true
#    serviceUrl:
#      defaultZone: http://eureka-0.eureka.default.svc.cluster.local:8761/eureka