server:
  port: 8060

management:
  tracing:
    sampling:
      probability: 1.0

spring:
  application:
    name: api-gateway
  config:
    import: "optional:configserver:http://localhost:8081"

  cloud:
    gateway:
      routes:
        - id: register-service
          uri: lb://register-service
          predicates:
            - Path=/ecommerce/register/**

        - id: login-service
          uri: lb://login-service
          predicates:
            - Path=/login/**


eureka:
  instance:
    preferIpAddress: true
    hostname: eureka-0
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-0.eureka.default.svc.cluster.local:8761/eureka


