
server:
  port: 8085

spring:
  datasource:
    url: jdbc:mysql://localhost:8889/Microservices
    username: root
    password: root

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  tracing:
    sampling:
      probability: 1.0

