server:
  port: 8761

spring:
  application:
    name: service-registry


eureka:
  instance:
    hostname: "${HOSTNAME}.eureka"
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: "${EUREKA_SERVER_ADDRESS}"