




spring:
  jpa:
    hibernate:
        ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:8889/Microservices
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: register-service
  config:
    import: "optional:configserver:http://localhost:8081"




#
#  spring.jpa.hibernate.ddl-auto=update
#  spring.datasource.url=jdbc:mysql://localhost:8889/Microservices
#  spring.datasource.username=root
#  spring.datasource.password=root
#  spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#pring.jpa.show-sql: true

