

spring:
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:mysql://localhost:8889/Logins
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: login-service
  config:
    import: "optional:configserver:http://localhost:8081"



